name: bloom_a1
description: "A Flutter project for plant care and assistance."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  animations: ^2.0.7
  logging: ^1.0.0
  http: ^0.13.4
  speech_to_text: ^7.0.0
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  get: ^4.7.2
  intl: ^0.18.0
  geolocator: ^10.0.0  # إضافة حزمة geolocator
  #flutter_spinkit: ^5.1.0  # إضافة حزمة flutter_spinkit
  #connectivity: ^3.0.6 # إضافة حزمة connectivity للتحقق من الاتصال بالإنترنت قبل جلب بيانات الطقس
  sqflite: ^2.4.2
  path: ^1.9.1
  weather: ^2.0.1
  geocoding: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo_bloom.png
    - assets/images/plant1.png
    - assets/images/plant2.png
    - assets/images/chat.png
    - assets/class_mapping.json
    - assets/plant_info.json
    - assets/plant_model.tflite